# basic setup
highlighter: rouge
permalink: /:categories/:title
encoding: utf-8
timezone: America/Sao_Paulo

# site identification
title: Biblioteca do Cicerone
tagline: Cthulhu Fthagn!
description: >-
    Seja bem-vindo ao meu acervo sobre
    os abismos da loucura da narração.
    Bons pesadelos!
url: https://bibliotecadocicerone.github.io/
baseurl: '/'
github:
    repo: https://bibliotecadocicerone.github.io/

# my identification
author:
    name: 'Luís Cavalheiro'
    email: bibliotecadocicerone@gmail.com
    telegram: lcavalheiro
    github_username: bibliotecadocicerone
# avatar

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
