# page configuration
highlighter: rouge
markdown: kramdown
plugins:
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap
timezone: America/Sao_Paulo
encoding: utf-8
excerpt_separator: <!-- excerpt -->
paginate: 3

# page information
title: Biblioteca do Cicerone
tagline: 'Bons pesadelos!'
description: >-
    Seja bem-vindo ao meu acervo sobre
    os abismos da loucura dos jogos de
    interpretação de papéis.
baseurl: "" 
url: "" 

# personal information
author:
    name: Luís Cavalheiro
    email: bibliotecadocicerone@gmail.com
    telegram: lcavalheiro
    github_username: bibliotecadocicerone
#    avatar:
