# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
name:                'Biblioteca do Cicerone'
title:               'Biblioteca do Cicerone'
tagline:             'A biblioteca virtual do Cicerone'
description:         'Seja benvindo à Biblioteca do Cicerone Luís Cavalheiro. Aqui você encontrará artigos, informações, materiais e mesas narradas por ele. Todos os materiais disponíveis aqui estão licenciados sob a Creative Commons CC-BY-NC-SA 4.0. Clique em [Sobre](about.md) para maiores informações.'
url:                 http://bibliotecadocicerone.github.io
baseurl:             /
markdown:            rdiscount
theme:               lanyon
plugins:
    - jekyll-feed

# Post setup
show_excerpts:       true
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Luís Cavalheiro
  url:               https://bibliotecadocicerone.github.io
  email:             bibliotecadocicerone@gmail.com

# Custom vars
version:             1.0.0
